name: Build and Push Docker Image to GCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
env:
  PROJECT_ID: symbolic-object-383000
  IMAGE_NAME: testweb_v2
  IMAGE_TAG: latest
  DOCKERFILE_PATH: ./Dockerfile
  GAR_LOCATION: asia-northeast3
  REPOSITORY: trivy-repo
  
  
jobs:
  build_and_push:
    permissions:
      id-token: write
      contents: read
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: 'actions/checkout@v3'
    
    # 1. Docker Image Build
#     - name: Build Docker image
#       run: |
#         docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        
    # 2. WIF 적용 & Image Push (GCR)
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: projects/195937949357/locations/global/workloadIdentityPools/github-actions/providers/dqa-d-ingest-cd-provider-v2
        service_account: 'dqa-d-sc-data-cd-github@symbolic-object-383000.iam.gserviceaccount.com'
        audience: 'https://github.com/chee2e/web_wif_v2'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.1
    

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://${{ env.GAR_LOCATION }}-docker.pkg.dev
     
    # Build the Docker image 
    - name: Build
      run: |-
        docker build \
          --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" \
          --build-arg GITHUB_SHA="${{ github.sha }}" \
          --build-arg GITHUB_REF="${{ github.ref }}" \
          .
         
    - name: Push to Artifact Registry
      run: |-
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
