name: Build and Push Docker Image to GCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
env:
  PROJECT_ID: symbolic-object-383000
  IMAGE_NAME: testweb_v2
  DOCKERFILE_PATH: ./Dockerfile
  SERVICE_ACCOUNT_EMAIL: dqa-d-sc-ingest-cicd-github@symbolic-object-383000.iam.gserviceaccount.com
  audience: 'https://github.com/chee2e/web_wif_v2'
  
  
jobs:
  build_and_push:
    permissions:
      id-token: write
      contents: read
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/195937949357/locations/global/workloadIdentityPools/github-actions/providers/dqa-d-ingest-cd-provider-2'
        service_account: 'dqa-d-sc-ingest-cicd-github@symbolic-object-383000.iam.gserviceaccount.com'

    - name: Configure Docker client
      run: |
        gcloud auth configure-docker -q
        
    - name: Build and push Docker image
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: latest
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

#     - name: Build Docker image
#       run: |
#         docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
#       env:
#         TAG: latest
    
#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
        
#     - name: Push Docker image to GCR
#       run: |
#         docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
#       env:
#         TAG: latest
